acme_dynamic_form:
    resource: "@AcmeDynamicFormBundle/Controller/"
    prefix:   /dynamicform
    type: annotation

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /dynamicform
        permanent: true